### ISSUE TITLE
fiftyonedegrees.c:230:35: error: ‘fiftyonedegrees_global’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by 0i** [whatvn/php7-51degrees#1]
/bin/bash /root/src/php7-51degrees/libtool --mode=compile cc  -I. -I/root/src/php7-51degrees -DPHP_ATOM_INC -I/root/src/php7-51degrees/include -I/root/src/php7-51degrees/main -I/root/src/php7-51degrees -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/deviceDetection  -DHAVE_CONFIG_H  -g -O2   -c /root/src/php7-51degrees/fiftyonedegrees.c -o fiftyonedegrees.lo
libtool: compile:  cc -I. -I/root/src/php7-51degrees -DPHP_ATOM_INC -I/root/src/php7-51degrees/include -I/root/src/php7-51degrees/main -I/root/src/php7-51degrees -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/deviceDetection -DHAVE_CONFIG_H -g -O2 -c /root/src/php7-51degrees/fiftyonedegrees.c  -fPIC -DPIC -o .libs/fiftyonedegrees.o
/root/src/php7-51degrees/fiftyonedegrees.c: In function ‘zm_startup_fiftyonedegrees’:
/root/src/php7-51degrees/fiftyonedegrees.c:230:35: error: ‘fiftyonedegrees_global’ undeclared (first use in this function)
     fiftyonedegrees_init_globals(&fiftyonedegrees_global TSRMLS_CC);
                                   ^
/root/src/php7-51degrees/fiftyonedegrees.c:230:35: note: each undeclared identifier is reported only once for each function it appears in
Makefile:195: recipe for target 'fiftyonedegrees.lo' failed

**Comment by whatvn** [comment]
Sorry, it took me too long to notice this issue

can you post your environment specs: 
- php version
- php configuration parameters 

Thanks

**Comment by matiit** [comment]
@whatvn 
It seems I am having the same issue, so I am gonna share my specs:

```bash
PHP 7.0.18-0ubuntu0.17.04.1 (cli) (built: Apr 26 2017 23:59:48) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.17.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```
Config options:

```bash

php-config --configure-options
--includedir=/usr/include 
--mandir=/usr/share/man 
--infodir=/usr/share/info 
--disable-silent-rules 
--libdir=/usr/lib/x86_64-linux-gnu 
--libexecdir=/usr/lib/x86_64-linux-gnu 
--disable-maintainer-mode 
--disable-dependency-tracking 
--prefix=/usr 
--enable-cli
--disable-cgi 
--disable-phpdbg 
--with-config-file-path=/etc/php/7.0/cli 
--with-config-file-scan-dir=/etc/php/7.0/cli/conf.d 
--build=x86_64-linux-gnu 
--host=x86_64-linux-gnu 
--config-cache 
--cache-file=/build/php7.0-QG2e5Y/php7.0-7.0.18/config.cache 
--libdir=${prefix}/lib/php 
--libexecdir=${prefix}/lib/php 
--datadir=${prefix}/share/php/7.0 
--program-suffix=7.0 
--sysconfdir=/etc 
--localstatedir=/var 
--mandir=/usr/share/man 
--disable-all 
--disable-debug 
--disable-rpath 
--disable-static 
--with-pic 
--with-layout=GNU 
--without-pear 
--enable-filter 
--with-openssl=yes 
--with-pcre-regex=/usr 
--enable-hash 
--with-mhash=/usr 
--enable-libxml 
--enable-session 
--with-system-tzdata 
--with-zlib=/usr 
--with-zlib-dir=/usr 
--enable-dtrace 
--enable-pcntl 
--with-libedit=shared,/usr build_alias=x86_64-linux-gnu host_alias=x86_64-linux-gnu 
CFLAGS=-g -O2 
-fdebug-prefix-map=/build/php7.0-QG2e5Y/php7.0-7.0.18=. 
-fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -Wall -pedantic
 -fsigned-char -fno-strict-aliasing -g
```

Please do tell if you need any more details.

**Comment by matiit** [comment]
Hope that helps guys! 

https://github.com/whatvn/php7-51degrees/pull/2

**Comment by whatvn** [comment]
@matiit Thank for you report and fix. I've merged your pull request.
